baseURL = "https://take-shige.github.io/hugoblogchallenge/index.html"
languageCode = "ja"
title = "上手くいった"
contentDir = "post"
canonifyurls = true
theme = "ananke"
publishDir = "docs"
[taxonomies]
tag = "tags"
